# Generated by Django 3.1.2 on 2020-10-16 06:31

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animalabuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('DOB', models.DateField(null=True)),
                ('Age', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=120, null=True)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('Offense', models.TextField(blank=True, null=True)),
                ('convictiondate', models.DateField(null=True)),
                ('expirationdate', models.DateField(null=True)),
                ('image', models.URLField(null=True)),
            ],
        ),
    ]
