# Generated by Django 3.1.2 on 2020-10-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalabuse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalabuse',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animalabuse',
            name='convictiondate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animalabuse',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
