# Generated by Django 3.1.1 on 2020-09-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalabuse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalabuse',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animalabuse',
            name='Age',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='animalabuse',
            name='DOB',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animalabuse',
            name='Offense',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animalabuse',
            name='convictiondate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='animalabuse',
            name='expirationdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='animalabuse',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='animalabuse',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
