# Generated by Django 3.1.2 on 2020-11-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalabuse', '0002_auto_20201016_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalabuse',
            name='data_source',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='animalabuse',
            name='source_description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='animalabuse',
            name='source_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
