# Generated by Django 3.1.1 on 2020-09-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalabuse', '0003_animalabuse_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalabuse',
            name='expirationdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='animalabuse',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
