# Generated by Django 3.1.2 on 2020-10-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalabuse', '0004_auto_20200929_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalabuse',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
