# Generated by Django 3.1.2 on 2020-11-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalabuse', '0004_auto_20201121_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalabuse',
            name='data_source',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
