# Generated by Django 3.1.2 on 2020-11-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalabuse', '0005_auto_20201121_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalabuse',
            old_name='data_source',
            new_name='dataSource',
        ),
        migrations.RenameField(
            model_name='animalabuse',
            old_name='source_description',
            new_name='sourceDescription',
        ),
        migrations.RenameField(
            model_name='animalabuse',
            old_name='source_link',
            new_name='sourceLink',
        ),
    ]
