# Generated by Django 3.1.2 on 2020-10-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalabuse', '0005_auto_20201006_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalabuse',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
