# Generated by Django 3.1.2 on 2020-10-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalabuse', '0006_animalabuse_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense', models.CharField(choices=[('FELONY CRUELTY TO ANIMALS', 'Felony Cruelty to Animal'), ('TOUCH/STRIKE/CAUSE HARM-POLICE/FIRE/SAR ANIMAL', 'Touch/Strike/Cause Harm-Police/Fire/Sar Animal'), ('AGGRAVATED CRUELTY TO ANIMALS', 'Aggravated Cruelty To Animals'), ('CONFINEMENT/ABANDONMENT OF ANIMAL', 'Confinement/Abandonment Of Animal'), ('ANIMAL FIGHTING', 'Animal Fighting'), ('CRUELTY TO POLICE DOG OR HORSE', 'Cruelty To Police Dog Or Horse'), ('CRIMINAL OFFENSES AGAINST ANIMALS', 'Criminal Offenses Against Animals'), ('SEXUAL ACTIVITIES INVOLVING ANIMALS', 'Sexual Activities Involving Animals'), ('OTHER', 'Other')], max_length=200, null=True)),
            ],
        ),
    ]
