# Generated by Django 3.1.2 on 2020-10-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalabuse', '0007_offensetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OffenseType',
        ),
    ]
