# Generated by Django 3.1.2 on 2020-10-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalabuse', '0009_auto_20201009_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalabuse',
            name='Age',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
