# Generated by Django 3.1.2 on 2020-10-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalabuse', '0010_auto_20201012_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalabuse',
            name='Age',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
    ]
