# Generated by Django 3.1.2 on 2020-10-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalabuse', '0011_auto_20201012_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalabuse',
            name='image',
            field=models.URLField(default='https://www.bengi.nl/wp-content/uploads/2014/10/no-image-available1.png', null=True),
        ),
    ]
